pip install -e . --no-deps
pip install diffusers==0.37.0 --no-deps
pip install scikit-learn==1.6.1 --no-deps
pip install scikit-image==0.25.2 --no-deps
pip install albumentations==1.4.10 --no-deps
pip install opencv-python==4.11.0.86 --no-deps
pip install albucore==0.0.13 --no-deps
pip install opencv-python-headless==4.10.0.84 --no-deps
pip install peft==0.18.1 --no-deps
pip install bitsandbytes==0.48.0 --no-deps
pip install ml_collections==1.1.0 --no-deps
pip install imageio==2.36.0 --no-deps
pip install lazy-loader==0.4 --no-deps
pip install tifffile==2026.1.28 --no-deps
pip install joblib==1.5.3 --no-deps
pip install threadpoolctl==3.6.0 --no-deps
pip install simsimd==6.5.12 --no-deps
pip install stringzilla==4.6.0 --no-deps

pip install paddlepaddle-gpu==2.6.2 --no-deps
pip install paddleocr==2.9.1 --no-deps
pip install python-Levenshtein==0.27.3 --no-deps
pip install levenshtein==0.27.3 --no-deps
pip install astor==0.8.1 --no-deps
pip install opt-einsum==3.3.0 --no-deps
pip install beautifulsoup4==4.14.3 --no-deps
pip install soupsieve==2.8.3 --no-deps
pip install cython==3.2.4 --no-deps
pip install fire==0.7.1 --no-deps
pip install termcolor==3.3.0 --no-deps
pip install imgaug==0.4.0 --no-deps
pip install lmdb==1.7.5 --no-deps
pip install opencv-contrib-python==4.11.0.86 --no-deps
pip install pyclipper==1.4.0 --no-deps
pip install python-docx==1.2.0 --no-deps
pip install rapidfuzz==3.14.3 --no-deps
pip install shapely==2.1.2 --no-deps
pip install tomli==2.4.0 --no-deps

apt-get install -y libglib2.0-0
apt-get install -y libgl1
